dist: xenial
language: python
sudo: false

python:
  - '2.7'
  - '3.5'
  - '3.6'
  - '3.7'
  - '3.8'

install:
  - pip install coveralls flake8 nose>=1.3.0
  - python setup.py install
script:
  - flake8 .
  - python setup.py nosetests
  - python setup.py build_sphinx
after_success:
  coveralls
