language: python
python:
  - '2.7'
  - '3.3'
  - '3.4'
  - '3.5'
  - '3.6'
install:
  - pip install coveralls coverage flake8 nose>=1.3.0
  - python setup.py install
script:
  - flake8 .
  - coverage run setup.py test
  - coverage report --fail-under=100
after_success:
  coveralls
